apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: anchorpeer-allchannel-carrier
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://3.90.251.127:8200
      authpath: localcarrier-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CrcCChgKFggCGgYImOLApAYiCmFsbGNoYW5uZWwSmgIKlwIKCmFsbGNoYW5uZWwSYxJhCgtBcHBs
      aWNhdGlvbhJSCAESTgoKY2Fycmllck1TUBJAGgcKA01TUBIAIg8KC0VuZG9yc2VtZW50EgAiCwoH
      UmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSABqjARKgAQoLQXBwbGljYXRpb24SkAEI
      ARKLAQoKY2Fycmllck1TUBJ9CAEaBwoDTVNQEgAaMQoLQW5jaG9yUGVlcnMSIhIYChYKEXBlZXIw
      LmNhcnJpZXItbmV0EIs3GgZBZG1pbnMiCwoHV3JpdGVycxIAIgoKBkFkbWlucxIAIg8KC0VuZG9y
      c2VtZW50EgAiCwoHUmVhZGVycxIAKgZBZG1pbnM=

