apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hdfc-ca
  namespace: hdfc
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: hdfc-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: hdfc
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
 
    server:
      name: ca
      tlsstatus: true
      admin: hdfc-admin 
  
    storage:
      storageclassname: hdfcsc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://23.20.229.51:8200
      authpath: localhdfc-auth
      secretcert: secretsv2/data/crypto/peerOrganizations/hdfc/ca?ca.hdfc-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/hdfc/ca?hdfc-CA.key
      secretadminpass: secretsv2/data/credentials/hdfc/ca/hdfc?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: bank.com
