apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-hdfc-peer0
  namespace: hdfc
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: joinchannel-peer0-join-allchannel-hdfc-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: hdfc
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.hdfc:7051
      localmspid: hdfcMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://54.196.243.208:8200
      authpath: localhdfc-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/hdfc/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/hdfc/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain:7050
