apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-acme-peer0
  namespace: acme
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: joinchannel-peer0-join-allchannel-acme-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: acme
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.acme:7051
      localmspid: acmeMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://20.193.143.232:8200
      authpath: localacme-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/acme/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/acme/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain:7050
