apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-ca
  namespace: supplychain
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: supplychain
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: supplychain-admin
        
    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://54.196.243.208:8200
      authpath: localsupplychain-auth
      secretcert: secretsv2/data/crypto/ordererOrganizations/supplychain/ca?ca.supplychain-cert.pem
      secretkey: secretsv2/data/crypto/ordererOrganizations/supplychain/ca?supplychain-CA.key
      secretadminpass: secretsv2/data/credentials/supplychain/ca/supplychain?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: orderer
      external_url_suffix: bank.com
